export const THEME_LIST = [
  { item: "가족", color: "blue", english: "family" },
  { item: "혼자", color: "blue", english: "solo" },
  { item: "친구", color: "blue", english: "friends" },
  { item: "단체", color: "blue", english: "group" },
  { item: "커풀", color: "blue", english: "couple" },
  { item: "자연", color: "green", english: "nature" },
  { item: "휴식", color: "green", english: "relaxation" },
  { item: "축제", color: "green", english: "festival" },
  { item: "액티비티", color: "green", english: "activity" },
  { item: "스포츠 관람", color: "green", english: "sports viewing" },
  { item: "체험", color: "green", english: "experience" },
  { item: "쇼핑", color: "green", english: "shopping" },
  { item: "유적지", color: "green", english: "historic site" },
];
